"""
Django settings for geoportal project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


GDAL_LIBRARY_PATH = config(
    "GDAL_LIBRARY_PATH",
    default=r"C:\Program Files\GDAL\gdal.dll",
)
GDAL_BASE_DIR = Path(GDAL_LIBRARY_PATH).parent
GEOS_LIBRARY_PATH = config(
    "GEOS_LIBRARY_PATH",
    default=r"C:\Program Files\GDAL\geos_c.dll",
)


def _coerce_gdal_resource(configured_path: str, resource_name: str) -> str:
    """Keep GDAL/PROJ resources aligned with the configured GDAL install."""
    resource_path = Path(configured_path)
    fallback_path = GDAL_BASE_DIR / resource_name

    if not fallback_path.exists():
        return str(resource_path)

    try:
        if resource_path.resolve(strict=False).is_relative_to(
            GDAL_BASE_DIR.resolve(strict=False)
        ):
            return str(resource_path)
    except OSError:
        pass

    return str(fallback_path)


GDAL_BIN_PATH = config(
    "GDAL_BIN_PATH",
    default=str(GDAL_BASE_DIR),
)
GDAL_DATA = _coerce_gdal_resource(
    config("GDAL_DATA", default=str(GDAL_BASE_DIR / "gdal-data")),
    "gdal-data",
)
PROJ_LIB = _coerce_gdal_resource(
    config("PROJ_LIB", default=str(GDAL_BASE_DIR / "projlib")),
    "projlib",
)

if os.name == "nt":
    dll_dirs = {
        str(GDAL_BASE_DIR),
        str(Path(GEOS_LIBRARY_PATH).parent),
        GDAL_BIN_PATH,
    }
    for dll_dir in dll_dirs:
        if dll_dir and Path(dll_dir).exists():
            os.add_dll_directory(dll_dir)

# Force the GIS runtime to use the project's configured GDAL/PROJ data
# instead of conflicting system-wide PostgreSQL/PostGIS variables.
os.environ["GDAL_DATA"] = GDAL_DATA
os.environ["PROJ_LIB"] = PROJ_LIB
os.environ["PROJ_DATA"] = PROJ_LIB


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-p93k4cbfnwcl0wnq6u3tv)zh=vt$w8n+z1d%g#8nir%b(@^tsl"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.gis',
    'capas'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "geoportal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "geoportal.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default=5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
