# Generated by Django 6.1 on 2026-08-17 18:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testgeometry",
            options={
                "verbose_name": "Test de Geometria",
                "verbose_name_plural": "Tests de Geometria",
            },
        ),
        migrations.AlterField(
            model_name="testgeometry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AlterField(
            model_name="testgeometry",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                srid=4326, verbose_name="Geometria"
            ),
        ),
        migrations.CreateModel(
            name="UploadedLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre de la capa"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripcion"),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="layers/%Y/%m/", verbose_name="Archivo geoespacial"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        choices=[("shp", "Shapefile ZIP"), ("geojson", "GeoJSON")],
                        editable=False,
                        max_length=20,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "source_epsg",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="EPSG original",
                    ),
                ),
                (
                    "storage_epsg",
                    models.IntegerField(
                        default=4326,
                        editable=False,
                        verbose_name="EPSG de almacenamiento",
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Tipo de geometria",
                    ),
                ),
                (
                    "feature_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Numero de elementos"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="SHA-256",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("valid", "Valido"),
                            ("processed", "Procesado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        editable=False,
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "validation_message",
                    models.TextField(
                        blank=True,
                        editable=False,
                        verbose_name="Resultado de validacion",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de carga"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultima actualizacion"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_layers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario que realizo la carga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capa cargada",
                "verbose_name_plural": "Capas cargadas",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UploadedFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Geometria"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Atributos"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="capas.uploadedlayer",
                        verbose_name="Capa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elemento geografico",
                "verbose_name_plural": "Elementos geograficos",
            },
        ),
    ]
